services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fushun-web
    ports:
      - "8080:8080"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fushun-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
